create table if not exists crawler_run (
    id           bigint generated by default as identity primary key,
    started_at   timestamptz not null default now(),
    finished_at  timestamptz null,
    status       varchar(32) not null,
    source       varchar(64) not null,
    note         varchar(255) null
);

create table if not exists ingestion_run (
    ingestion_run_id bigserial primary key,
    crawler_run_id   bigint not null references crawler_run(id),
    started_at       timestamptz not null default now(),
    finished_at      timestamptz null,
    status           varchar(32) not null,
    error_code       varchar(128) null,
    error_message    varchar(512) null
);

create table if not exists product (
    id           bigint generated by default as identity primary key,
    external_id  varchar(64) null,
    name         varchar(512) not null,
    url          varchar(1024) not null,
    slug         varchar(512) null,
    pack_value   numeric(18, 6) null,
    pack_unit    varchar(16) null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz null
);

create table if not exists product_catalog
(
    id
    bigint
    generated
    by
    default as
    identity
    primary
    key,
    source
    varchar
(
    50
) not null,
    url varchar
(
    1024
) not null,
    normalized_url varchar
(
    1024
) not null,
    external_id varchar
(
    200
) null,
    slug varchar
(
    300
) null,
    first_discovered_at timestamptz not null,
    last_discovered_at timestamptz not null,
    last_checked_at timestamptz null,
    next_check_at timestamptz null,
    reserved_at timestamptz null,
    reserved_until timestamptz null,
    reserved_by varchar
(
    200
) null,
    is_active boolean not null default true,
    consecutive_errors integer not null default 0,
    created_at timestamptz not null default now
(
),
    updated_at timestamptz not null default now
(
),
    constraint ck_product_catalog_consecutive_errors_non_negative check
(
    consecutive_errors
    >=
    0
)
    );

create table if not exists product_catalog_refresh
(
    id
    bigint
    generated
    always as
    identity
    primary
    key,
    source
    varchar
(
    50
) not null,
    discovery_source varchar
(
    50
) not null,
    started_at timestamptz not null,
    finished_at timestamptz null,
    status varchar
(
    20
) not null,
    discovered_count integer not null default 0,
    accepted_count integer not null default 0,
    inserted_count integer not null default 0,
    updated_count integer not null default 0,
    deactivated_count integer not null default 0,
    reactivated_count integer not null default 0,
    error_code varchar
(
    100
) null,
    error_message varchar
(
    1000
) null,
    created_at timestamptz not null default now
(
),
    updated_at timestamptz not null default now
(
),
    constraint ck_product_catalog_refresh_status
    check
(
    status
    in
(
    'running',
    'ok',
    'error',
    'cancelled'
)),
    constraint ck_product_catalog_refresh_counts_non_negative
    check
(
    discovered_count
    >=
    0
    and
    accepted_count
    >=
    0
    and
    inserted_count
    >=
    0
    and
    updated_count
    >=
    0
    and
    deactivated_count
    >=
    0
    and
    reactivated_count
    >=
    0
)
    );

create table if not exists price_collect_queue (
    id                  bigint generated by default as identity primary key,
    run_id              bigint not null references crawler_run(id),
    product_catalog_id bigint null,
    url                 varchar(1024) not null,
    status              varchar(32) not null,
    attempt             integer not null default 0,
    max_attempts        integer not null default 0,
    next_attempt_at     timestamptz null,
    reserved_at         timestamptz null,
    lease_until         timestamptz null,
    reserved_by         varchar(128) null,
    idempotency_key     varchar(128) null,
    last_error_code     varchar(64) null,
    last_http_status    integer null,
    last_error_message  varchar(512) null,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz null,
    finished_at         timestamptz null
);

create table if not exists price_snapshot (
    id           bigint generated by default as identity primary key,
    run_id       bigint not null references crawler_run(id),
    product_id   bigint not null references product(id),
    captured_at  timestamptz not null,
    price        numeric(18, 2) null,
    old_price    numeric(18, 2) null,
    promo_flag   boolean not null default false,
    in_stock     boolean not null default false,
    queue_id     bigint null references price_collect_queue(id)
);

create table if not exists crawl_error (
    id             bigint generated by default as identity primary key,
    run_id         bigint not null references crawler_run(id),
    queue_id       bigint null references price_collect_queue(id),
    product_id     bigint null references product(id),
    url            varchar(1024) null,
    error_code     varchar(64) null,
    http_status    integer null,
    error_message  varchar(512) null,
    created_at     timestamptz not null default now()
);

create table if not exists db_routine_script
(
    script_name
    varchar
(
    255
) primary key,
    script_hash varchar
(
    64
) not null,
    applied_at timestamptz not null default now
(
)
    );

alter table product_catalog
    add column if not exists reserved_at timestamptz null;
alter table product_catalog
    add column if not exists reserved_until timestamptz null;
alter table product_catalog
    add column if not exists reserved_by varchar (200) null;
alter table product_catalog
    add column if not exists last_seen_refresh_id bigint null;
alter table product_catalog
    add column if not exists deactivated_at timestamptz null;
alter table product_catalog
    add column if not exists reactivated_at timestamptz null;
alter table price_collect_queue
    add column if not exists product_catalog_id bigint null;

do
$$
begin
    if
not exists (
        select 1
        from pg_constraint
        where conname = 'fk_price_collect_queue_product_catalog'
          and conrelid = 'price_collect_queue'::regclass
    ) then
alter table price_collect_queue
    add constraint fk_price_collect_queue_product_catalog
        foreign key (product_catalog_id)
            references product_catalog (id)
            on delete restrict;
end if;
end;
$$;

do
$$
begin
    if
not exists (
        select 1
        from pg_constraint
        where conname = 'fk_product_catalog_last_seen_refresh'
          and conrelid = 'product_catalog'::regclass
    ) then
alter table product_catalog
    add constraint fk_product_catalog_last_seen_refresh
        foreign key (last_seen_refresh_id)
            references product_catalog_refresh (id)
            on delete restrict;
end if;
end;
$$;

create unique index if not exists ux_product_url on product(url);
create index if not exists ix_product_external_id on product(external_id);
create unique index if not exists ux_product_catalog_source_normalized_url
    on product_catalog(source, normalized_url);
create index if not exists ix_product_catalog_due
    on product_catalog(is_active, next_check_at, reserved_until, last_checked_at, id);
create index if not exists ix_product_catalog_last_discovered_at
    on product_catalog(last_discovered_at);
create index if not exists ix_product_catalog_last_seen_refresh_id
    on product_catalog(last_seen_refresh_id);
create index if not exists ix_product_catalog_reservation
    on product_catalog(reserved_until, id)
    where reserved_until is not null;
create unique index if not exists ux_product_catalog_refresh_running_source
    on product_catalog_refresh(source)
    where status = 'running';
create unique index if not exists ux_price_collect_queue_run_url on price_collect_queue(run_id, url);
create index if not exists ix_price_collect_queue_product_catalog_id
    on price_collect_queue(product_catalog_id);
create unique index if not exists ux_price_collect_queue_idempotency
    on price_collect_queue(idempotency_key)
    where idempotency_key is not null;
create index if not exists ix_price_collect_queue_pick on price_collect_queue(status, next_attempt_at, id);
create index if not exists ix_price_collect_queue_lease on price_collect_queue(status, lease_until);
create index if not exists ix_price_snapshot_product_captured_at_desc on price_snapshot(product_id, captured_at desc);
create index if not exists ix_price_snapshot_run_id on price_snapshot(run_id);
create index if not exists ix_crawl_error_run_id on crawl_error(run_id);
create index if not exists ix_crawl_error_product_id on crawl_error(product_id);
create index if not exists ix_crawler_run_source_started_at_desc on crawler_run(source, started_at desc);
