create table if not exists crawler_run (
    id           bigint generated by default as identity primary key,
    started_at   timestamptz not null default now(),
    finished_at  timestamptz null,
    status       varchar(32) not null,
    source       varchar(64) not null,
    note         varchar(255) null
);

create table if not exists ingestion_run (
    ingestion_run_id bigserial primary key,
    crawler_run_id   bigint not null references crawler_run(id),
    started_at       timestamptz not null default now(),
    finished_at      timestamptz null,
    status           varchar(32) not null,
    error_code       varchar(128) null,
    error_message    varchar(512) null
);

create table if not exists product (
    id           bigint generated by default as identity primary key,
    external_id  varchar(64) null,
    name         varchar(512) not null,
    url          varchar(1024) not null,
    slug         varchar(512) null,
    pack_value   numeric(18, 6) null,
    pack_unit    varchar(16) null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz null
);

create table if not exists price_collect_queue (
    id                  bigint generated by default as identity primary key,
    run_id              bigint not null references crawler_run(id),
    url                 varchar(1024) not null,
    status              varchar(32) not null,
    attempt             integer not null default 0,
    max_attempts        integer not null default 0,
    next_attempt_at     timestamptz null,
    reserved_at         timestamptz null,
    lease_until         timestamptz null,
    reserved_by         varchar(128) null,
    idempotency_key     varchar(128) null,
    last_error_code     varchar(64) null,
    last_http_status    integer null,
    last_error_message  varchar(512) null,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz null,
    finished_at         timestamptz null
);

create table if not exists price_snapshot (
    id           bigint generated by default as identity primary key,
    run_id       bigint not null references crawler_run(id),
    product_id   bigint not null references product(id),
    captured_at  timestamptz not null,
    price        numeric(18, 2) null,
    old_price    numeric(18, 2) null,
    promo_flag   boolean not null default false,
    in_stock     boolean not null default false,
    queue_id     bigint null references price_collect_queue(id)
);

create table if not exists crawl_error (
    id             bigint generated by default as identity primary key,
    run_id         bigint not null references crawler_run(id),
    queue_id       bigint null references price_collect_queue(id),
    product_id     bigint null references product(id),
    url            varchar(1024) null,
    error_code     varchar(64) null,
    http_status    integer null,
    error_message  varchar(512) null,
    created_at     timestamptz not null default now()
);

create table if not exists db_routine_script
(
    script_name
    varchar
(
    255
) primary key,
    script_hash varchar
(
    64
) not null,
    applied_at timestamptz not null default now
(
)
    );

create unique index if not exists ux_product_url on product(url);
create index if not exists ix_product_external_id on product(external_id);
create unique index if not exists ux_price_collect_queue_run_url on price_collect_queue(run_id, url);
create unique index if not exists ux_price_collect_queue_idempotency
    on price_collect_queue(idempotency_key)
    where idempotency_key is not null;
create index if not exists ix_price_collect_queue_pick on price_collect_queue(status, next_attempt_at, id);
create index if not exists ix_price_collect_queue_lease on price_collect_queue(status, lease_until);
create index if not exists ix_price_snapshot_product_captured_at_desc on price_snapshot(product_id, captured_at desc);
create index if not exists ix_price_snapshot_run_id on price_snapshot(run_id);
create index if not exists ix_crawl_error_run_id on crawl_error(run_id);
create index if not exists ix_crawl_error_product_id on crawl_error(product_id);
create index if not exists ix_crawler_run_source_started_at_desc on crawler_run(source, started_at desc);
