name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.311

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Version Check
        run: |
          dotnet --info
          dotnet msbuild VarPrice.Application/VarPrice.Application.csproj -t:GetBuildVersion -getProperty:Version -getProperty:AssemblyVersion -getProperty:FileVersion -getProperty:AssemblyInformationalVersion
          dotnet pack VarPrice.Application/VarPrice.Application.csproj --configuration Release --no-build --output ./artifacts

      - name: Test
        run: dotnet test --configuration Release --no-build
